model_name_or_path: Bingsu/my_roberta_untrained
dataset_name: Bingsu/my-korean-training-corpus-half
use_auth_token: true
optimizer_name: madgrad
batch_size: 8
gradient_clip_val: 1.0
accumulate_grad_batches: 2
num_workers: 32
log_every_n_steps: 200
max_seq_length: 508
seed: 20220915
